### ISSUE TITLE
As a user I would like to have a settings page for each of my wallets

### ISSUE THREAD

**Issue by Mathyn** [Smilo-platform/Smilo-Wallet#12]
The settings page should allow me to:
- Toggle 'hide balances' (when enabled balances are not shown in my wallet)
- Backup the wallet
- Delete the wallet
- 2FA?

Some things we need to decide:
- How will creating a backup of your wallet work?
- How will we implement 2FA?

**Comment by elkanroelen** [comment]
Mathyn,

The settings page should be able to import or export a backup.
For the prototype it is enough to export a file with a private key.
And enough to import the private key.

In the future it wil have: 
private keys, public keys, scripts (which correspond to addresses), key metadata (e.g. labels), private and public transactions related to the wallet. It also includes the encrypted HD seed and the derivation paths for each private key.

Backup: A file containing a wallet’s private key information. Backups can be exported from a wallet or imported to a wallet.
Export: The process of creating a file containing a wallet’s private key data. Exported keys can be imported to a new/different wallet to give access to the exported associated with the exported private key(s).
Import: The process of gaining control of Coins via an exported backup. Wallets can import private keys via text files or QR code scanning.
