### ISSUE TITLE
FAQ 'How secure is it?' question is empty

### ISSUE THREAD

**Issue by Mathyn** [Smilo-platform/Smilo-Wallet#168]

**Comment by Mathyn** [comment]
So far no content has been provided to the developers. Will pick this up with marketing!

**Comment by NickelvdMortel** [comment]
The SmiloWallet will never send your private keys or encrypted keystore files across the network. They will be stored locally on your device. Even if an attacker were to gain access to your devices local storage, they would still need your Smilo password in order to gain access to your funds.

**Comment by Mathyn** [comment]
Thank you @NickelvdMortel we will add it to the FAQ!
