### ISSUE TITLE
As a User I would like to have a FAQ page

### ISSUE THREAD

**Issue by Mathyn** [Smilo-platform/Smilo-Wallet#9]
A simple page with often asked questions. What questions should be included?

**Comment by NickelvdMortel** [comment]
What is a SmiloWallet?
Smilo's web wallet is a free, open-source, client-side interface. You remain in full control of your keys and your funds. We cannot recover your funds or freeze your account if you visit a phishing site or lose your private key.

Is the SmiloWallet a bank?
No, the SmiloWallet is not a bank. The SmiloWallet is just an interface which allows you to communicate with Smilo’s blockchain network. When you create an account on SmiloWallet, you are generating a cryptographic set of numbers: your private key and your public key (address). The handling of your keys happens entirely on your computer, inside your browser. We never transmit, receive or store your private key, password, or other account information.

How secure is it?


How can I trust the SmiloWallet?
The SmiloWallet source code is available on Github for anyone to verify. We serve the wallet over SSL (https) which eliminates the possibility of tampering with the code between our servers and your browser. Still not sure? Download the latest standalone release on our Github releases page and run the SmiloWallet locally. Alternatively, you can build directly from the source.

What if I lose my private key or forget my encrypted Keystore file’s password?
You remain in full control of your keys and your funds. We cannot recover your funds or freeze your account if you visit a phishing site or lose your private key.

We are not responsible for any loss.
SmiloWallet.io is under active development. While we have thoroughly tested the wallet, there is always the possibility that something unexpected happens which causes your funds to be lost. Do not invest more than you are willing to lose.

**Comment by Mathyn** [comment]
The question "How secure is it?" is currently missing an answer. Is this on purpose?

**Comment by Mathyn** [comment]
Another question: the question 'How can I trust the SmiloWallet?' refers to the use of SSL for extra security. It appears this questions is only scoped to the browser version of the wallet because this does not really apply to the Android and iOS versions (e.g. you download through an app store, on Android you can even sideload the app quite easily). How can we best adjust this question for this?
